/* eslint-disable no-unused-vars */
module.exports.LOGGEDIN = 'loggedIn'
module.exports.ID = 'userId'
module.exports.SIGNATURE = 'signature'
module.exports.EMAIL = 'email'
module.exports.FIRSTNAME = 'first'
module.exports.LASTNAME = 'last'
module.exports.CITY = 'city'
module.exports.AGE = 'age'
module.exports.URL = 'url'
