/* eslint-disable no-unused-vars */
module.exports.SIGNED = '/petition/signed'
module.exports.PETITION = '/petition'
module.exports.REGISTER = '/register'
module.exports.SIGNERS = '/petition/signers'
module.exports.LOGIN = '/login'
module.exports.LOGOUT = '/logout'
module.exports.PROFILE = '/profile'
module.exports.CITY = '/petition/signers/:city'
module.exports.EDITPROFILE = '/edit-profile'
module.exports.DELETESIG = '/delete-module.exports'
